### ISSUE TITLE
ERROR: Lock file '/data/letsencrypt/lock' present, aborting.

### ISSUE THREAD

**Issue by cweilemann** [troykelly/hassio-addons-letsencrypt-lexicon#10] opened 2021-12-14 03:38 UTC
I'm trying to run this addon with Namecheap DNS and am running into two problems... The first was a 400 error, even though I copied my API Key, IP, and username exactly as from Proxmox -- perhaps this is because this addon has the API key field named `token`? -- but now I am receiving the following when I run the addon:

```sh
...
[21:33:15] INFO: Requesting domains from LetsEncrypt
# Home Assistant Domains
<subdomain>.<subdomain>.<subdomain>.tld > <domain_with_underscores>
# END Home Assistant Domains
# INFO: Using main config file /etc/dehydrated/config
ERROR: Lock file '/data/letsencrypt/lock' present, aborting.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

I have an SSH addon installed and there is no directory under `/data` called `letsencrypt/`, thus no `lock` file.

Would this `lock` file live in another location?

**Comment by maur8ino** [comment] 2022-01-20 09:33
I got the same error just this morning and I just reinstalled the add-on and it solved the issue.
Just be sure to save your configuration first 😉

**Comment by troykelly** [comment] 2022-09-22 05:46
Closing - waaaay old and can't reproduce.
Please reopen if needed.

**Closed as completed by troykelly** 2022-09-22 05:46 UTC
